import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { chooseMenuItem } from "./menu-helpers";
import webCorpus from "../../src/assets/web-corpus.json" with { type: "json" };

test("inserts complete WEB selections, undoes once, and preserves citations through reopen and output", async ({ page }) => {
  await page.goto("/?dbs=offline");
  const editor = page.getByRole("textbox", { name: "Document editor" });
  await expect(page.getByRole("button", { name: /Scripture translation/ })).toHaveText("WEB");
  await editor.click();
  await page.keyboard.type("John 3:36-4:2 ");
  const reference = page.locator(".scripture-reference");
  await expect(reference).toHaveText("John 3:36-4:2");
  await reference.hover();
  const expectedCrossChapter = [webCorpus.books.JHN[2][35], ...webCorpus.books.JHN[3].slice(0, 2)].join(" ").replace(/\s+/gu, " ").trim();
  await expect(page.getByRole("tooltip")).toContainText(expectedCrossChapter);
  await reference.click();
  await expect(editor).toContainText(expectedCrossChapter);
  await expect(page.locator(".scripture-citation")).toHaveText("(John 3:36-4:2, WEB)");
  await page.keyboard.press("Control+z");
  await expect(editor).toHaveText("John 3:36-4:2 ");
  await expect(page.locator(".scripture-citation")).toHaveCount(0);
  await reference.click();
  await expect(page.locator(".scripture-citation")).toHaveCount(1);

  await editor.press("Control+End");
  await page.keyboard.press("Enter");
  await page.keyboard.type("John 3:16,18-20 ");
  await reference.click();
  await expect(page.locator(".scripture-citation").last()).toHaveText("(John 3:16,18-20, WEB)");
  const expectedList = [webCorpus.books.JHN[2][15], ...webCorpus.books.JHN[2].slice(17, 20)].join(" ").replace(/\s+/gu, " ").trim();
  await expect(editor.locator("p").last()).toHaveText(`${expectedList} (John 3:16,18-20, WEB) `);

  await editor.press("Control+End");
  await page.keyboard.press("Enter");
  await page.keyboard.type("Psalm 23 ");
  await reference.click();
  await expect(page.locator(".scripture-citation").last()).toHaveText("(Psalms 23, WEB)");
  const expectedChapter = webCorpus.books.PSA[22].join(" ").replace(/\s+/gu, " ").trim();
  await expect(editor.locator("p").last()).toHaveText(`${expectedChapter} (Psalms 23, WEB) `);
  const text = await editor.innerText();
  const metadata = await page.locator(".scripture-citation").evaluateAll((nodes) => nodes.map((node) => node.getAttribute("data-reference")));
  expect(JSON.parse(metadata[0]!)).toMatchObject({ chapter: 3, chapterEnd: 4, verseStart: 36, verseEnd: 2 });
  expect(JSON.parse(metadata[1]!)).toMatchObject({ additionalRanges: [{ chapter: 3, verseStart: 18, verseEnd: 20 }] });
  expect(JSON.parse(metadata[2]!)).toMatchObject({ wholeChapter: true });
  await page.keyboard.press("Control+s");
  await expect(page.getByRole("status")).toContainText("Saved Untitled.verseform");
  await page.keyboard.press("Control+n");
  await page.keyboard.press("Control+o");
  await expect(editor).toHaveText(text);
  expect(await page.locator(".scripture-citation").evaluateAll((nodes) => nodes.map((node) => node.getAttribute("data-reference")))).toEqual(metadata);
  await expect(reference).toHaveCount(0);
  await chooseMenuItem(page, "File", /^Save PDF/);
  const output = page.getByRole("dialog", { name: "Export PDF" });
  await expect(output.getByRole("button", { name: "Export PDF" })).toBeEnabled();
  await expect(output).toContainText(expectedCrossChapter);
  await expect(output).toContainText("World English Bible (Public Domain)");
  await output.getByRole("button", { name: "Cancel" }).click();
  await expect(editor).toHaveText(text);
});

test("warns about complete invalid references locally and never offers a partial insertion", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("button", { name: /Scripture translation/ })).toHaveText("NASB");
  await page.evaluate(() => {
    const tracked = window as typeof window & { __passageRequests: number };
    tracked.__passageRequests = 0;
    window.addEventListener("verseform:fake-provider-request", () => { tracked.__passageRequests += 1; });
  });
  const editor = page.getByRole("textbox", { name: "Document editor" });
  await editor.click();
  await page.keyboard.type("John 3:16,18");
  await expect(page.locator(".scripture-reference")).toHaveCount(0);
  await page.keyboard.type(" ");
  await expect(page.locator(".scripture-reference")).toHaveText("John 3:16,18");
  await page.keyboard.press("Control+a");
  await page.keyboard.type("John 3:1-4:15. John 3:16,999. John 3:16:18 ");
  const invalid = page.locator(".scripture-reference-invalid");
  await expect(invalid).toHaveText(["John 3:1-4:15", "John 3:16,999", "John 3:16:18"]);
  await expect(page.locator(".scripture-reference")).toHaveCount(0);
  await page.keyboard.press("F6");
  await expect(invalid.first()).toBeFocused();
  await expect(page.getByRole("tooltip")).toContainText("50 verses across chapters");
  await page.keyboard.press("Enter");
  await invalid.nth(1).click();
  await invalid.nth(2).click();
  await expect(editor).toHaveText("John 3:1-4:15. John 3:16,999. John 3:16:18 ");
  await expect(page.locator(".scripture-citation")).toHaveCount(0);
  expect(await page.evaluate(() => (window as typeof window & { __passageRequests: number }).__passageRequests)).toBe(0);
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"]).analyze()).violations).toEqual([]);
});

test("rejects a stale multi-chapter insertion after the reference changes", async ({ page }) => {
  await page.goto("/?lookupDelay=350");
  await expect(page.getByRole("button", { name: /Scripture translation/ })).toHaveText("NASB");
  const editor = page.getByRole("textbox", { name: "Document editor" });
  await editor.click();
  await page.keyboard.type("John 3:36-4:2 ");
  await page.locator(".scripture-reference").click();
  await expect(page.getByRole("status")).toContainText("Looking up John 3:36-4:2");
  await editor.press("Control+End");
  await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await page.keyboard.type("3 ");
  await expect(page.getByRole("status")).toContainText("changed");
  await expect(editor).toHaveText("John 3:36-4:3 ");
  await expect(page.locator(".scripture-citation")).toHaveCount(0);
});

test("keeps a long chapter preview within the window and lets the keyboard scroll before inserting all verses", async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 620 });
  await page.goto("/?dbs=offline");
  const editor = page.getByRole("textbox", { name: "Document editor" });
  await editor.click();
  await page.keyboard.type("Psalm 119 ");
  await page.keyboard.press("F6");
  const reference = page.locator(".scripture-reference");
  await expect(reference).toBeFocused();
  const preview = page.getByRole("tooltip");
  await expect(preview).toContainText(webCorpus.books.PSA[118][175]);
  const bounds = await preview.boundingBox();
  expect(bounds!.y).toBeGreaterThanOrEqual(0);
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(620);
  await page.keyboard.press("PageDown");
  expect(await preview.evaluate((node) => node.scrollTop)).toBeGreaterThan(0);
  await expect(reference).toBeFocused();
  await page.keyboard.press("PageUp");
  expect(await preview.evaluate((node) => node.scrollTop)).toBe(0);
  await reference.hover();
  await preview.hover();
  await page.mouse.wheel(0, 400);
  await expect.poll(() => preview.evaluate((node) => node.scrollTop)).toBeGreaterThan(0);
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"]).analyze()).violations).toEqual([]);
  await page.screenshot({ path: "artifacts/vfm-170-long-chapter-preview.png" });
  await page.keyboard.press("Enter");
  const expected = webCorpus.books.PSA[118].join(" ").replace(/\s+/gu, " ").trim();
  await expect(editor).toHaveText(`${expected} (Psalms 119, WEB) `);
  await expect(page.locator(".scripture-citation")).toHaveCount(1);
});
